name: Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@deskree-inc'

      - name: Install NPM Dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}

      - name: Run tests and generate JEST coverage report
        run: npm run test
        env:
          APP_BASE_PATH: /v1/
          PROJECT_ID: 'test'
          INTEGRATION_NAME: 'test'
